import { createHash } from "node:crypto";
import type { RiskClassification, SkillCapability, SkillManifest, SkillPermission, SpecialistRole } from "../../../src/types.js";

type Definition = {
  id: string; name: string; description: string; roles: SpecialistRole[]; coordinates: string[];
  capabilities: SkillCapability[]; adapters: string[]; risk: RiskClassification; permissions: SkillPermission[];
  instructions: string; validation?: string[];
};

const definitions: Definition[] = [
  { id: "repository-manager", name: "Repository Manager", description: "Clones, inspects, branches, checkpoints, commits, and prepares repositories safely.", roles: ["planner", "integrator", "devops"], coordinates: ["Scout", "Plan", "Build", "Integrate", "Stage"], capabilities: ["filesystem", "command", "git", "github"], adapters: ["filesystem", "command", "git", "github"], risk: "workspace_write", permissions: ["filesystem_read", "filesystem_write", "command_execute", "git_write"], instructions: "Inspect repository state before every mutation. Work in an Orbit-owned worktree, preserve user changes, checkpoint before integration, and never push main or master.", validation: ["git status --short", "git rev-parse --show-toplevel"] },
  { id: "stack-detector", name: "Stack Detector", description: "Detects frameworks, package managers, commands, and repository conventions.", roles: ["planner", "architect"], coordinates: ["Scout", "Validate", "Plan"], capabilities: ["filesystem"], adapters: ["filesystem"], risk: "read", permissions: ["filesystem_read"], instructions: "Inspect manifests and conventions without modifying the repository." },
  { id: "project-bootstrapper", name: "Project Bootstrapper", description: "Verifies tools, installs dependencies, and establishes a passing baseline.", roles: ["architect", "devops"], coordinates: ["Validate", "Plan", "Build"], capabilities: ["filesystem", "command", "packages", "tests"], adapters: ["filesystem", "command", "packages", "tests"], risk: "workspace_write", permissions: ["filesystem_read", "filesystem_write", "command_execute"], instructions: "Use the detected package manager and lockfile. Do not replace dependency state without evidence." },
  { id: "planner", name: "Planner", description: "Turns objectives into requirements, tasks, dependencies, and acceptance criteria.", roles: ["planner"], coordinates: ["Select", "Validate", "Plan"], capabilities: ["filesystem"], adapters: ["filesystem"], risk: "read", permissions: ["filesystem_read"], instructions: "Produce traceable, testable requirements and explicit dependencies." },
  { id: "implementation", name: "Implementation", description: "Performs scoped frontend, backend, database, and infrastructure changes.", roles: ["frontend", "backend", "database", "devops", "integrator"], coordinates: ["Build", "Integrate"], capabilities: ["filesystem", "command", "tests"], adapters: ["filesystem", "command", "tests"], risk: "workspace_write", permissions: ["filesystem_read", "filesystem_write", "command_execute"], instructions: "Change only files required by the task and validate proportionally to risk." },
  { id: "test-repair", name: "Test and Repair", description: "Runs checks, diagnoses failures, and repairs with bounded retries.", roles: ["qa", "frontend", "backend", "integrator"], coordinates: ["Build", "Review", "QA"], capabilities: ["command", "tests"], adapters: ["command", "tests"], risk: "workspace_write", permissions: ["filesystem_read", "filesystem_write", "command_execute"], instructions: "Capture failing evidence first. Stop after the configured repair limit." },
  { id: "browser-qa", name: "Browser QA", description: "Replays user journeys and captures browser evidence.", roles: ["qa", "accessibility"], coordinates: ["QA", "Stage"], capabilities: ["browser", "tests"], adapters: ["browser", "tests"], risk: "read", permissions: ["filesystem_read", "command_execute"], instructions: "Test primary journeys, console errors, and reduced motion; redact captured user data." },
  { id: "security-reviewer", name: "Security Reviewer", description: "Reviews secrets, dependencies, permissions, migrations, and unsafe operations.", roles: ["security"], coordinates: ["Review", "Security", "Production Gate"], capabilities: ["filesystem", "command", "git"], adapters: ["filesystem", "command", "git"], risk: "read", permissions: ["filesystem_read", "command_execute"], instructions: "Treat credentials and production data as restricted. Report evidence and block unsafe promotion." },
  { id: "accessibility-reviewer", name: "Accessibility Reviewer", description: "Validates keyboard, semantics, contrast, and motion preferences.", roles: ["accessibility", "qa"], coordinates: ["Review", "QA"], capabilities: ["browser"], adapters: ["browser"], risk: "read", permissions: ["filesystem_read", "command_execute"], instructions: "Verify the primary journey using keyboard and accessibility semantics." },
  { id: "research-scout", name: "Research Scout", description: "Produces cited evidence-backed Signals from approved sources.", roles: ["planner", "product_designer"], coordinates: ["Scout", "Select", "Validate"], capabilities: ["research"], adapters: ["research"], risk: "read", permissions: ["network_read"], instructions: "Use approved sources, preserve citations, distinguish inference, and never mutate external systems." },
  { id: "product-analyst", name: "Product Analyst", description: "Assesses user value, friction, alternatives, effort, and confidence.", roles: ["planner", "product_designer"], coordinates: ["Scout", "Select", "Validate"], capabilities: ["research"], adapters: ["research"], risk: "read", permissions: ["filesystem_read", "network_read"], instructions: "Tie recommendations to user value and explicit evidence." },
  { id: "constellation-facilitator", name: "Constellation Facilitator", description: "Coordinates up to three Stars and produces a clear recommendation.", roles: ["planner", "reviewer"], coordinates: ["Select", "Review"], capabilities: ["provider"], adapters: ["provider"], risk: "read", permissions: ["filesystem_read"], instructions: "Expose disagreements and assumptions; never fabricate consensus." },
  { id: "release-manager", name: "Release Manager", description: "Bumps versions, assembles evidence, packages releases, and prepares PRs.", roles: ["integrator", "devops"], coordinates: ["Integrate", "Stage", "Production Gate"], capabilities: ["command", "git", "github", "tests"], adapters: ["command", "git", "github", "tests"], risk: "external_mutation", permissions: ["filesystem_read", "filesystem_write", "command_execute", "git_write", "external_mutation"], instructions: "Release only verified revisions through PRs. Never push directly to main or master." },
  { id: "staging-operator", name: "Staging Operator", description: "Deploys exact revisions to approved staging targets.", roles: ["devops"], coordinates: ["Stage"], capabilities: ["deployment", "observability"], adapters: ["deployment", "observability"], risk: "external_mutation", permissions: ["external_mutation", "deployment"], instructions: "Deploy only configured staging targets and record the exact revision and health evidence." },
  { id: "production-gatekeeper", name: "Production Gatekeeper", description: "Validates PR, staging evidence, checks, rollback, and authority.", roles: ["reviewer", "security", "devops"], coordinates: ["Production Gate"], capabilities: ["github", "deployment", "observability", "approvals"], adapters: ["github", "deployment", "observability", "approvals"], risk: "external_mutation", permissions: ["external_mutation", "deployment", "production"], instructions: "Require verified PR, exact staged revision, passing checks, rollback readiness, and production authority." },
  { id: "observability-analyst", name: "Observability Analyst", description: "Inspects approved logs and health signals for regressions.", roles: ["performance", "devops"], coordinates: ["Stage", "Production Gate", "Report"], capabilities: ["observability"], adapters: ["observability"], risk: "read", permissions: ["network_read"], instructions: "Read only approved project-scoped telemetry and redact user data." },
  { id: "dependency-maintainer", name: "Dependency Maintainer", description: "Assesses and validates dependency updates and security impact.", roles: ["security", "integrator"], coordinates: ["Validate", "Build", "Security"], capabilities: ["research", "packages", "tests"], adapters: ["research", "packages", "tests"], risk: "workspace_write", permissions: ["filesystem_read", "filesystem_write", "command_execute", "network_read"], instructions: "Respect lockfiles, review changelogs, and validate compatibility before retaining updates." },
  { id: "incident-recovery", name: "Incident and Recovery", description: "Stops unsafe work, restores Waypoints, retries safely, or rolls back staging.", roles: ["devops", "integrator", "security"], coordinates: ["Build", "Integrate", "QA", "Security", "Stage", "Report"], capabilities: ["git", "deployment", "observability", "notifications"], adapters: ["git", "deployment", "observability", "notifications"], risk: "workspace_write", permissions: ["filesystem_read", "filesystem_write", "git_write", "deployment"], instructions: "Prefer safe abort and Waypoint restoration. Never roll back production without explicit authority." }
];

function manifest(definition: Definition): SkillManifest {
  const unsigned = {
    schemaVersion: 1 as const, ...definition, source: "builtin" as const, version: "1.0.0",
    providers: ["codex", "claude"] as const, platforms: ["linux", "darwin", "win32"] as const,
    requiredCapabilities: definition.capabilities, requiredAdapters: definition.adapters, dependencies: [],
    inputSchema: { type: "object" }, outputSchema: { type: "object" }, preconditions: ["Orbit repository boundary is valid"],
    successCriteria: ["Declared evidence is captured", "Policy remains satisfied"], validationCommands: definition.validation ?? [],
    timeoutSeconds: 1800, maxRetries: 3, checkpoint: definition.risk !== "read",
    rollback: "Restore the latest valid Waypoint or leave changes isolated for review.",
    redaction: ["credentials", "tokens", "provider homes", "hidden reasoning", "personal data"],
    evidence: ["policy decision", "adapter operations", "validation results", "Waypoint"]
  };
  return { ...unsigned, roles: definition.roles, coordinates: definition.coordinates, providers: [...unsigned.providers], platforms: [...unsigned.platforms], integrity: createHash("sha256").update(JSON.stringify(unsigned)).digest("hex"), compatibility: ">=0.2.0 <1.0.0" };
}

export const BUILTIN_SKILLS = definitions.map(manifest);
